### ISSUE TITLE
Dúvida sobre o mongoDB

### ISSUE THREAD

**Issue by andvalle** [glaucia86/demo-mean-azurefunctions#5]
Olá Glaucia,
Tentei usar o mongodb compass em um win 7 32 bit porém vi que não tem como instalar,  existe outra forma de fazer o curso só com o mongodb ?

**Comment by glaucia86** [comment]
Eita.... não sei dizer @andvalle. 
Porque como vc usa Win 7 teria que dar uma olhada na doc do Mongo.
